pipeline {

    agent {
        label "linux"
    }
    parameters {
        booleanParam(name: 'TagLatest', defaultValue: false, description: 'Tag this image as latest')
    }
    options {
        buildDiscarder(logRotator(numToKeepStr: '30', artifactNumToKeepStr: '30'))
        timestamps()
        disableConcurrentBuilds()
    }
    environment {
        projectName  = "xsa_ap_deploy"
        deployTo = "sit"
        version = "1.0.0.${env.BUILD_NUMBER}"
        suffix = "${env.GIT_COMMIT}-${env.GIT_BRANCH.replace('/', '-')}"
        packageVersion = "${version}-${suffix}"
        jobName = "xsa_ap_deploy"
        artifactoryServerId = "artifactory"
    }

    stages {
        stage ("Stash files") {
            steps {
                stash includes: "Infrastructure/deployment/app-router/*", name: "appRouter", useDefaultExcludes: false
                stash includes: "Infrastructure/deployment/app/*", name: "app", useDefaultExcludes: false
                stash includes: "Infrastructure/deployment/app/framework/*", name: "appFramework", useDefaultExcludes: false
                stash includes: "Infrastructure/octopus/*", name: "octopus", useDefaultExcludes: false
            }
        }

        stage ("Publish Artifacts") {
            agent {
                docker {
                    image "octopusdeploy/octo"
                    args '--entrypoint=\'\''
                }
		    }
            steps {
                unstash "appRouter"
                unstash "app"
                unstash "appFramework"
                unstash "octopus"

                sh "rm -rf dataART.${projectName}.${version}"
                fileOperations([
                    folderCopyOperation(
                        sourceFolderPath: "Infrastructure",
                        destinationFolderPath: "$WORKSPACE/dataART.${projectName}.${version}/")
                ])

                sh """ octo pack --id="dataART.${projectName}" --version="${packageVersion}" --basepath="$WORKSPACE/dataART.${projectName}.${version}" --outFolder=$WORKSPACE """

                rtUpload(
                    spec: '''{ "files": [
                        {
                            "pattern": "dataART.${projectName}.${packageVersion}.nupkg",
                            "target": "octopus-dataarten/",
                            "props" : "deployed=true"
                        }
                    ] }''',
                    buildNumber: "${packageVersion}", buildName: "dataART.${projectName}",
                    serverId: "${artifactoryServerId}"
                )
                rtPublishBuildInfo(buildNumber: "${packageVersion}", buildName: "dataART.${projectName}", serverId: "${artifactoryServerId}")
            }
        }
    }
}